# Generated by Django 5.1.2 on 2024-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_email_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='default_subject', max_length=100),
        ),
    ]
