# Generated by Django 5.1.3 on 2024-11-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='urls',
            field=models.JSONField(default=list),
        ),
    ]
